name: flutfire
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  
  flutter: 
    sdk: flutter
  # flutter_bloc:
  # formz: ^0.4.0
  # equatable: ^2.0.3
  # authentication_repository:
  #   path: packages/authentication_repository
  # user_repository:
  #   path: packages/user_repository
  firebase_auth: ^3.1.3
  get: ^4.3.8
  google_sign_in: ^5.1.1
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.5
  cloud_firestore: ^2.5.3
  firebase_messaging: ^10.0.8
  font_awesome_flutter: ^9.1.0
  otp_text_field: ^1.1.1

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  # bloc_test:
  # mocktail: ^0.1.0

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

