name: flutfire
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_messaging: ^11.2.3
  firebase_storage: ^10.2.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  get: ^4.5.1
  google_sign_in: ^5.2.1
  image_picker: ^0.8.4+4
  otp_text_field: ^1.1.1
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
