name: flutfire
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  font_awesome_flutter: ^9.2.0
  get: ^4.6.1
  google_sign_in: ^5.2.3
  image_picker: ^0.8.4+4
  otp_text_field: ^1.1.1
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
